### ISSUE TITLE
Build error with GHC 8.4.1-alpha1

### ISSUE THREAD

**Issue by asr** [feuerbach/tasty#196]
GHC 8.4.1-alpha1 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2017-December/015235.html). While testing [Agda](https://github.com/agda/agda) with this version of GHC, I got various errors on tasty-silver (master branch) related to missing instances of `Semigroup` like this:

```
$ cabal install
...
Test/Tasty/Options.hs:81:10: error:
    • No instance for (Semigroup OptionSet)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid OptionSet’
   |
81 | instance Monoid OptionSet where
   |          ^^^^^^^^^^^^^^^^
Failed to install tasty-0.12
```

These errors are reported as warnings in GHC 8.0.2/8.2.2 using the `-Wsemigroup` flag:

```
$ cabal install --force-reinstalls --ghc-options='-Wsemigroup -Werror'
```

So, fixing these warnings on GHC 8.0.2/8.2.2 fix the errors on GHC 8.4.1-alpha1.

Blocking https://github.com/agda/agda/issues/2878.

**Comment by feuerbach** [comment]
Thanks for the report. It should fixed on master now — could you try it with ghc 8.4? If it works, I'll make a release.

**Comment by asr** [comment]
Thanks for the fix!

Testing with GHC 8.4.1-alpha1 I got various warnings like this:

```
Test/Tasty/Options.hs:88:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘<>’
    • In the instance declaration for ‘Semigroup OptionSet’
```
I will create a PR fixing these warnings.

For knowing the warnings in GHC 8.0.2/8.2.2, I realised it's better to use the `-Wcompat` flag (sorry about that).

**Comment by asr** [comment]
> I will create a PR fixing these warnings.

Done. See https://github.com/feuerbach/tasty/pull/197

**Comment by asr** [comment]
> could you try it with ghc 8.4? If it works, I'll make a release.

Modulo some dependencies (but `tasty.cabal` is ready), I could compile with GHC 8.4.1-alpha1.

**Comment by feuerbach** [comment]
Wait, that's weird. Do you know why these warnings appear?

I relied on the default implementation of `<>` (https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Semigroup.html) and indeed got no such warnings under earlier ghcs.

Have they removed the default method in 8.4?

**Comment by asr** [comment]
> Have they removed the default method in 8.4?

They changed the defaults. In 8.4, `mappend` is defined as `(<>)`:

```
class Semigroup a => Monoid a where
...
        -- __NOTE__: This method is redundant and has the default
        -- implementation @'mappend' = '(<>)'@ since /base-4.11.0.0/.
        mappend :: a -> a -> a
        mappend = (<>)
```

**Comment by feuerbach** [comment]
Got it, thanks. I see why they did it, but it's a great way to silently break a lot of code (when people don't pay attention to warnings).

**Comment by feuerbach** [comment]
Should be fixed now — could you check?

**Comment by asr** [comment]
Fixed. Thanks!

**Comment by feuerbach** [comment]
Cool! I now released this as tasty-0.12.0.1.

**Comment by asr** [comment]
Great! Thanks for the release.
