### ISSUE TITLE
GHC 8.6.1: `getApp` not in scope

### ISSUE THREAD

**Issue by asr** [feuerbach/tasty#225]
```haskell
module Test where

import Test.Tasty.Runners

foo :: Ap f a -> f a
foo = getApp
```

Using GHC 8.6.1-alpha2 on the above example, I get the following error:

```bash
$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 8.6.0.20180714

$ ghc Test.hs
Test.hs:7:7: error:
    • Variable not in scope: getApp :: Ap f a -> f a
    • Perhaps you meant ‘getAp’ (imported from Test.Tasty.Runners)
  |
7 | foo = getApp
  |       ^^^^^^
```

Note that the example compiles with GHC 8.4.3.

Blocking https://github.com/agda/agda/issues/3160.

**Comment by asr** [comment]
I got the above error while preparing Agda for supporting GHC 8.6.1 and I tried to install the [tasty-silver](http://hackage.haskell.org/package/tasty-silver) library.

CC'ing @phile314.

**Comment by feuerbach** [comment]
I think #224 fixes it; could you try with master?

I don't understand how this could happen though. `getAp` is defined right there in `Test.Tasty.Runners.Reducers`. What did they do to the compiler to make it disappear? (I don't have ghc 8.6 handy to test it myself.)

**Comment by asr** [comment]
> I think #224 fixes it; could you try with master?

The OP was using master (because tasty 1.1.0.2 doesn't build with GHC 8.6.1-alpha2).

> I don't understand how this could happen though. `getAp` is defined right there in `Test.Tasty.Runners.Reducers`.

Note that I didn't use `getAp` but `getApp`.

**Comment by feuerbach** [comment]
Ah I see. So your error is a consequence of #224. I guess I'll have to install 8.6 myself and see what's going on.

**Comment by feuerbach** [comment]
This should now be fixed in master — could you please try and let me know?

**Comment by asr** [comment]
Yes, it is fixed in master. Thanks!

**Comment by feuerbach** [comment]
Cool — released as tasty-1.1.0.3 now.

**Comment by asr** [comment]
Great!
